### ISSUE TITLE
Appears to hang on a large ticket set

### ISSUE THREAD

**Issue by TheTechmage** [markfinger/assembla#13]
I've found that when I'm trying to grab a single ticket, it is a lot quicker to call https://api.assembla.com/v1/spaces/space_id/tickets/ticket_number.json directly instead of waiting for the script to complete. In fact, after a few minutes I just hit ctrl+c.

```
from assembla import API
print 'API'
assembla = API(
    key='<snip>',
    secret='<snip>',
)
for space in assembla.spaces():
    print space['name']
print 'spaces'
space = assembla.spaces(name='my-space')[0]
print space['id']
print 'tickets'
ticket = space.ticket(number=10)

print 'end'
print '#{0} - {1}'.format(ticket['number'], ticket['summary'])
```

As you can see, my script is fairly simple. It's just the fact that I have so many tickets to go through, it takes for ever. It even seems like it hangs on me.

**Comment by markfinger** [comment]
Assembla paginates by default (around 1000 per page from memory), and calling Assembla.tickets will send successive requests until it's exhausted the tickets available, so I can imagine that a fairly large ticket set could be causing the issue you've experienced.

How many tickets do you have in the space? I've been testing against spaces with 500-1500 tickets.

**Comment by TheTechmage** [comment]
From the looks of it, about 7000. Might be more, not sure.

~Frostyfrog
From a friendly web page developer.
^.^

**Comment by markfinger** [comment]
Thanks.

So the use case that's causing issues is that you're trying to retrieve a single ticket? Are you traversing over the whole ticket set?

Would be good to wrap the API._get_json method in something that looks for model & kwarg (eg: Ticket & number) combinations so that we can hit some of the more esoteric API endpoints. Optimise ALL the things...

**Comment by TheTechmage** [comment]
Yeah, I'm trying to grab a single ticket. Trying to make something where
you enter a ticket number and it'll give you the info on that specific
ticket.

~Frostyfrog
From a friendly web page developer.
^.^

**Comment by markfinger** [comment]
Thanks for both the report and the clarification. I'll bump this when a solution's available.

**Comment by TheTechmage** [comment]
Thanks! =D

**Comment by markfinger** [comment]
Hi frostyfrog,

I created an space with ~3500 tickets and subsequently witnessed the problem you reported. Turns out it was a problem with a function's assumption that responses would be cached.

I've merged a fix into master which should prevent the problem from occurring. Are you able to test it?
