### ISSUE TITLE
Space.users returns 403

### ISSUE THREAD

**Issue by macwis** [markfinger/assembla#14]
Hi,

I've tried:

from assembla import API
assembla = API(
     # ...proper settings
)
space = assembla.spaces(name='_space_name')[0]
for user in space.users():
    print user['name']

Expected:
printed out list of user names

Current output:
Traceback (most recent call last):
  File "myfile.py", line 27, in <module>
    for user in space.users():
  File "/usr/local/lib/python2.6/dist-packages/assembla/lib.py", line 34, in wrapper
    results = func(class_instance)
  File "/usr/local/lib/python2.6/dist-packages/assembla/**init**.py", line 175, in users
    rel_path=self._build_rel_path('users'),
  File "/usr/local/lib/python2.6/dist-packages/assembla/__init__.py", line 109, in _get_json
    url,
Exception: Code 403 returned from `https://api.assembla.com/v1/spaces/_space_id/users.json?page=1`.

It might be Assembla issue, but before I contact them I would like to confirm.

Best regards!

**Comment by markfinger** [comment]
Thanks for the report, I'll take a look.

**Comment by markfinger** [comment]
Assembla docs seem to indicate it may be an OAuth issue...

"""
OAuth-token expired or other problem with the user authentication
HTTP header: status code 403 (Forbidden)
HTTP body: message: A more verbose explanation about why the authN failed
"""

In any case, unexpected status codes, such as a 403, should now print Assembla's reason for returning the status. 

With any luck, that should help you resolve the issue.

ref commit: c8546d1
