### ISSUE TITLE
keyword filtering does not work for stream

### ISSUE THREAD

**Issue by bitNomad** [markfinger/assembla#16]
According to the doc, Keyword arguments can be provided to filter the stream() results. Per /v1/activity these are: space_id, to, from, page, per_page

 A couple of issues here:
1. passing keywords does not appear to work  
   .stream(page=2)  
   .stream(per_page=25)
2. how are you supposed to pass the reserved word from?

**Comment by markfinger** [comment]
Hey hey, thanks for picking up on that.

The codebase has been fixed and I've updated the docs with a solution to your problem. PyPI's also been updated with the latest codebase.

https://github.com/markfinger/assembla#filtering-objects-with-keyword-arguments

Let me know if you have any problems with it.

Cheers,
Mark

**Comment by bitNomad** [comment]
Thanks for the speedy turnaround! My workaround was quite similar to your fix, except I was having trouble when stream was still wrapped by assembla_filter. 

The reason I specifically called out 'from' is because increasing the default number of results using 'per_page' triggers querying all the results, which is nice to have but might not be what is wanted. I'll file another issue, but no rush. 

Thanks again, 

```
 -- Calvin
```
