### ISSUE TITLE
increasing per_page triggers downloading all

### ISSUE THREAD

**Issue by bitNomad** [markfinger/assembla#17]
in API._get_json You explicitly call out

``` python
# If the number of results is divisible by the maximum limit per
# page, then we need to fetch the next page
```

However this is not necessarily the case nor does it match assembla. 

For example, the default activity query returns 10. In that scenario API.stream() and ...activity.json are equivalent. 

If this gets bumped to 25

``` python
assembla.stream(extra_params={
    'per_page': 25
})
```

_every activity is queried_ where running the same command ...activity.json?per_page=25 gives only those first 25 or activity.json?per_page=25&page=2 would give the second 25. 

It would be nice to have control of whether to make the recursive call to get more results or limit them to a single page. The workaround for forcing a limit is to define {'from': 'yyyy-mm-dd hh:mm'}

**Comment by markfinger** [comment]
The recursive trawling was originally a hack to pull in all of the tickets in a space, given the issues you're describing, it would make sense to hide it behind an opt-in flag passed to `API._get_json`.

I'll take a looksies
