### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by zoni** [markfinger/assembla#21]
Currently, this library fails to install entirely on Python 3 (3.3 in the case of my test). I would love to see Python 3 support so that I can use it in my own Python 3 projects.

**Comment by zoni** [comment]
It looks like this might actually be quite simple to do. The [py3 branch](https://github.com/zoni/assembla/tree/py3) on my fork appears to work fine, at a first glance. I was able to query spaces and tickets successfully.

I haven't tried actually modifying anything though, nor did I test other components like wiki and stuff.

**Comment by markfinger** [comment]
Cool, thanks for investigating it.

It would be fantastic if you could make a pull request with the changes on your branch.

**Comment by zoni** [comment]
I didn't want to open a pull request right away, since I basically hadn't given it any significant testing at all (and I haven't, still). But here you go! #22

**Comment by markfinger** [comment]
Thanks for that.
