### ISSUE TITLE
Supporting Extraction of Comments and Statuses from Tickets

### ISSUE THREAD

**Issue by PhilippeTrounev** [markfinger/assembla#23]
Hello,
 I was looking into the API and I am wondering if there a quick and dirty way I can implement the extraction of comments from tickets into the API. From what I understand the URL is composed  of api root, version and space, and I was wondering how I could extend it to iterate all the comments from the tickets url = '{0}/{1}/{2}{TICKET}comment.json?{3}'.format(

I am not that familiar with python sorry if it makes no sense..

Regards.
P.T.

**Comment by markfinger** [comment]
Hi,

I've added Ticket.comments, which should add the functionality that you need.

``` python
from assembla import API

assembla = API(
    # auth
)

space = assembla.spaces()[0]

ticket = space.tickets()[0]

comments = ticket.comments()
```

Just a heads up that the textual content that Assembla returns has some weird formatting, for an example see the `ticket_changes` property below...

```
(Pdb) comments[0].data
{u'comment': None, u'user_id': u'cd5j9MQNGr4lvReJe5cbCb', u'ticket_changes': u'--- \n- - status\n  - New\n  - Fixed\n', u'updated_at': u'2013-11-05T03:27:29Z', u'created_on': u'2013-11-05T03:27:29Z', u'ticket_id': 67200943, u'id': 395095943}
```

The new version's up on PyPi, so you should be able to use pip to get it.

Cheers,
Mark

**Comment by PhilippeTrounev** [comment]
Hello,
 Wow thank you Mark, you are awesome!

This is exactly I was looking now, now I can continue my work on my
assembla reporting tool.

Regards.
P.T.
