### ISSUE TITLE
Milestones don't appear to work

### ISSUE THREAD

**Issue by cybersimon** [markfinger/assembla#6]
This is most likely due to assembla changing their API.

**Comment by markfinger** [comment]
Yah, the wrapper probably needs to be updated to use their new API. Assembla doesn't have a great track record with stability or reliability, so it'd be good to get off the new deprecated API.

**Comment by markfinger** [comment]
Closing this as fixed.

I ran the unit tests against the version 1 codebase and it didn't pick up anything odd, so it may be quirk of assembla's filtering or somesuch.

The version 2 codebase is explicitly pulling in all milestones for a space, see: 20ce46fbbdbfc42204a7f1b31a4c05f48869953f
